config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :students, only: [:index, :new, :create]

end

app/models/student.rb
class Student < ActiveRecord::Base
  validates_presence_of :name
end

app/controllers/Welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @students = Student.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
  end

  def create
    student = Student.new(student_params)
    if student.save
      redirect_to :root , notice: "#{student.name} was added to the list."
    else
      flash.alert = "Student name cannot be blank."
      render :new
    end
  end

  protected

  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RandomStudent
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = notice
    = alert
    = yield

app/views/students/_student.html.haml
%li= student.name

app/views/students/new.html.haml
= simple_form_for Student.new do |f|
  = f.input :name
  = f.submit "Add Student"

app/views/welcome/index.html.haml
%h1 Welcome Aboard!

= link_to "Add a Student", new_student_path

%ul#students= render @students